<?php

namespace App\Services;

use Iqbalatma\LaravelUtils\Interfaces\ResponseCodeInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * @method static ResponseCodeInterface ERR_ROUTE_NOT_FOUND()
 */
class ResponseCode extends \Iqbalatma\LaravelUtils\ResponseCode
{
    protected const ERR_ROUTE_NOT_FOUND = "ERR_ROUTE_NOT_FOUND";
    public function __construct(string $name)
    {
        $this->name = $name;
        $this->value = constant(__CLASS__ . '::' . $name);
    }

    protected function mapHttpCode(): void
    {
//        $this->httpCode = match ($this->name) {
//            self::ERR_ROUTE_NOT_FOUND => Response::HTTP_NOT_FOUND,
//        };
        parent::mapHttpCode(); // TODO: Change the autogenerated stub
    }
}
